version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: what-food-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fooduserservice
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - what-food-network

  redis:
    image: redis:8-alpine
    container_name: what-food-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - what-food-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: what-food-rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    networks:
      - what-food-network

  user-service:
    image: gopherkhb/what-food-user-service:latest
    container_name: what-food-user-service
    restart: always
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  user-product-service:
    image: gopherkhb/what-food-user-product-service:latest
    container_name: what-food-user-product-service
    restart: always
    env_file:
      - ./user-product-service/.env
    volumes:
      - ./user-product-service/migrations:/app/migrations
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  notification-service:
    image: gopherkhb/what-food-notifaction-service:latest
    container_name: what-food-notification-service
    restart: always
    env_file:
      - ./notification-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  auth-service:
    image: gopherkhb/what-food-auth-service:latest
    container_name: what-food-auth-service
    restart: always
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  food-service:
    image: gopherkhb/what-food-food-service:latest
    container_name: what-food-food-service
    restart: always
    env_file:
      - ./food-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  ai-service:
    image: gopherkhb/what-food-ai-service:latest
    container_name: what-food-ai-service
    restart: always
    env_file:
      - ./ai-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  analytics-service:
    image: gopherkhb/what-food-analytics-service:latest
    container_name: what-food-analytics-service
    restart: always
    env_file:
      - ./analytics-service/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - what-food-network

  mail-service:
    image: gopherkhb/what-food-mail-service:latest
    container_name: what-food-mail-service
    restart: always
    env_file:
      - ./mail-service/.env
    depends_on:
      - rabbitmq
      - redis
    networks:
      - what-food-network

  api-gateway:
    image: gopherkhb/what-food-api-geteway:latest
    container_name: what-food-api-gateway
    restart: always
    env_file:
      - ./api-geteway/.env
    depends_on:
      - auth-service
      - user-service
      - user-product-service
      - food-service
      - ai-service
      - analytics-service
      - notification-service
      - mail-service
    ports:
      - "8082:8082"
    networks:
      - what-food-network

volumes:
  postgres_data:

networks:
  what-food-network:
    driver: bridge